export const MESSAGE_CODES = {
  SUCCESS: "SUCCESS",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  USER: {
    USER_NOT_FOUND:'USER_NOT_FOUND'
  }
};
