export const MESSAGE_CODES = {
  SUCCESS: "SUCCESS",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  USER: {
    USER_NOT_FOUND:'USER_NOT_FOUND',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_FIRST_NAME: 'INVALID_FIRST_NAME',
    INVALID_LAST_NAME: 'INVALID_LAST_NAME',
    REQUIRED_PASSWORD:'REQUIRED_PASSWORD',
    PASSWORD_MIN_LENGTH:'PASSWORD_MIN_LENGTH',
    CONFIRM_PASSWORD_NOT_MATCH: 'CONFIRM_PASSWORD_NOT_MATCH',
    INVALID_ROLE: 'INVALID_ROLE',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS'
  }
};
